### ISSUE TITLE
hi its not on HACS store

### ISSUE THREAD

**Issue by aoaaron** [binarylogic/trinnov-altitude-homeassistant#1]
Hi cant find it on HACS store.

any chance of a sexy remote front end like the altitude app? any chance of automatic daily restart option at 5AM?

**Comment by binarylogic** [comment]
Hi @aoaaron . I've submitted it for review and awaiting approval. In HACs, you need to add it as a "custom repository" for now. See this screenshot:

<img width="1074" alt="Screenshot 2024-04-14 at 9 37 43 AM" src="https://github.com/binarylogic/trinnov-altitude-homeassistant/assets/1663286/33cb652a-0c1d-468a-95fc-3b3d15938cd8">

> any chance of a sexy remote front end like the altitude app?

This is basically what the media player component is. Otherwise, Home Assistant doesn't provide remotes in the way you are thinking. I thought that too when I first started using Home Assistant. Instead, remotes are more like abstract entities you can use in automations, etc.

> any chance of automatic daily restart option at 5AM?

Yes, you can do this with home assistant, but why would you want to do that?
