### ISSUE TITLE
Request for HDR sensor

### ISSUE THREAD

**Issue by BarneyHam** [binarylogic/trinnov-altitude-homeassistant#7]
The integration is fantastic.

Would it be possible to add a sensor to provide info on video input - specifically if the video signal is an HDR signal or not?

**Comment by binarylogic** [comment]
Hi @BarneyHam, unfortunately the Trinnov Altitude API does not provide this information. [Here are the docs](https://github.com/binarylogic/py-trinnov-altitude/tree/master/docs) that Trinnov provided. If you see something in there that's not implemented, let me know. Otherwise, I would make a request with Trinnov directly.

Alternatively, I have a MadVR, which does provide this information. Hope that helps.
